name: cargo pgx test pgXX

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    env:
      ES_VERSION: "7.13.2"
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        version: [10, 11, 12, 13, 14]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v2

    - name: cargo version
      run: cargo --version

    # Remove old Postgres
    - name: remove old Postgres
      run: sudo apt-get remove -y postgres*

      # Update apt
    - name: update apt
      run: |
        sudo apt-get update -y -qq --fix-missing
        sudo apt-get install -y wget gnupg
        sudo bash -c 'echo deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main >> /etc/apt/sources.list.d/pgdg.list'
        sudo apt update

      # Install Postgres
    - name: install postgres
      run: sudo apt-get install -y clang-10 llvm-10 clang gcc make build-essential libz-dev zlib1g-dev strace libssl-dev pkg-config postgresql-${{ matrix.version }} postgresql-server-dev-${{ matrix.version }}

    # download Elasticsearch
    - name: download Elasticsearch
      run: curl -s https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}-linux-x86_64.tar.gz | tar xzf -
    - name: rename Elasticsearch
      run: mv elasticsearch-${ES_VERSION} elasticsearch

    # update cargo indexes so we're sure we get the latest things from 'git' repo dependencies
    - name: cargo update
      run: cargo update

      # install cargo-pgx
    - name: install cargo-pgx
      run: cargo install cargo-pgx

    # initialize pgx
    - name: cargo pgx init
      run: cargo pgx init --pg${{ matrix.version }}=`which pg_config`

    - name: cat config.toml
      run: cat ~/.pgx/config.toml

    - name: hack permissions
      run: sudo chmod a+rwx `pg_config --pkglibdir` `pg_config --sharedir`/extension /var/run/postgresql/

    # test our code
    - name: cargo test --all
      run: RUST_BACKTRACE=1 cargo test --all --no-default-features --features "pg${{ matrix.version }} pg_test" -- --nocapture
